### ISSUE TITLE
No requirements.txt or .gitignore

### ISSUE THREAD

**Issue by datavistics** [thiswillbeyourgithub/pdf2anki#1]
Add a requirements.txt to track python dependencies like requests.

Also missing a .gitignore.

**Comment by thiswillbeyourgithub** [comment]
I'm mostly self taught in python so I just learned what this was after reading your issue.

I added a file, can you confirm it's ok? `pip3 freeze` only returned requests so I guess subprocess re and pathlib are default.

edit : adding gitignore

**Comment by thiswillbeyourgithub** [comment]
is this better?

**Comment by datavistics** [comment]
Oh I was about to make a pull request :)

**Comment by datavistics** [comment]
But yeah the ones you named are built-in libraries.
