### ISSUE TITLE
Add the pdf dir and media folder as arguments

### ISSUE THREAD

**Issue by datavistics** [thiswillbeyourgithub/pdf2anki#4]
This way its not required to change the file to adjust to the user's requirements.

**Comment by thiswillbeyourgithub** [comment]
I totally agree.

They should be provided as argument and the whole pdftk + renaming procedure could be automated. I just don't have the time, even those simple things require much more work than even the average programmer.

edit : i mean I would probably do it in the next 6 months but that's really not my priority

**Comment by thiswillbeyourgithub** [comment]
sortof done
