### ISSUE TITLE
So, I'm fairly confused on how to use this. I've attempted to place the pdf into the place where I've installed the repository, and I've pip installed the requirements(which are all satisfied now), but the code for automating the burst tells me all of them are commands which are not recognized.

### ISSUE THREAD

**Issue by winterfate** [thiswillbeyourgithub/pdf2anki#5]
I am on Windows 10, I DO have AnkiConnect installed, I just can't seem to get this to do whatever it's supposed to do, the instructions are fairly vague and leave a lot of questions to be asked, and I can't tell where anything is actually supposed to go. Was very excited to try this after discovering it on the Anki subreddit.

**Comment by thiswillbeyourgithub** [comment]
Hi, back again after some vacation. I don't have much more time but I can provide a bit of assitance. Helping you will definitely help me formulate the README better so please don't hesitate to tell me.

I made this script to work on my setup that is on linux, I'm affraid this script requires quite some modification to work on windows.

It uses convert and pdftk, which are packages on linux.

Convert is used to turn the single page pdf to an image
pdftk is used to burst the pdf into single page pdf

It appears convert doesn't need to be used, and something like this https://www.roytuts.com/convert-pdf-to-image-using-python/ could be used to turn the pdf into an image.

Do you know any python coding by any chance?

**Comment by winterfate** [comment]
> Hi, back again after some vacation. I don't have much more time but I can provide a bit of assitance. Helping you will definitely help me formulate the README better so please don't hesitate to tell me.
> 
> I made this script to work on my setup that is on linux, I'm affraid this script requires quite some modification to work on windows.
> 
> It uses convert and pdftk, which are packages on linux.
> 
> Convert is used to turn the single page pdf to an image
> pdftk is used to burst the pdf into single page pdf
> 
> It appears convert doesn't need to be used, and something like this https://www.roytuts.com/convert-pdf-to-image-using-python/ could be used to turn the pdf into an image.
> 
> Do you know any python coding by any chance?

I do know Python, but I’ve been learning on Codecademy, and I’ve only learned about “for” loops amd “while” loops a couple weeks ago and am having difficulty iterating and completing the challenges presented to me. I need to figure out what I’m not knowing. I know, like, the basics of the basics maybe. Keywords: tuples, loops, lists, range, append, for loops, while loops, if then statements, list comprehension

I could just do a virtual machine for Linux, but my computer doesn’t like me doing that for some reason.

**Comment by thiswillbeyourgithub** [comment]
Yeah that's probably not quite enough knowledge of python. But close. You could make some good progress by trying to implement this though.

You have to use pdftk to turn a pdf into single pages pdf https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/

Then in this file : https://github.com/thiswillbeyourgithub/pdf2anki/blob/master/pdf2anki.py

the line 123 and 126 are launching linux terminal commands to first convert the pdf into an image then get the text from it.

You would need to find ways to use python for this instead of relying on launching linux commands. I didn't have the time to do it at the time but it doesn't seem very hard to do and would be quite the opportunity to learn I think

Let me know if you have any question

**Comment by thiswillbeyourgithub** [comment]
Hello, I modified the code quite a bit and you can now use it on windows quite easily I think. If you can give it a try and give me a feedback that might be helpful! I'm closing this but reopen it if needed.
